#!/usr/bin/python3
from subprocess

# checking active services and running 'if' statements against it for each service
p = subprocess.Popen([systemctl","list-units","--all","--state=active"], stdout=subprocess.PIPE)
(out1, err) = p.communicate()
                
# if sshd is found in out1 then print it's status
p = subprocess.Popen([systemctl","status","sshd"], stdout=subprocess.PIPE)
(out1, err) = p.communicate()
                      if ('sshd' in str(out1)):
                      print(out2)
