#!/usr/bin/python3
from subprocess import check_output

ssh_status = check_output('systemctl status sshd',shell=True,universal_newlines=True)

l = ssh_status.split("\n")

for i in l:
    if 'Active:' in i:
        print(i)
        testing123
